version: "3"
services:
  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    networks:
      - my-network
    volumes:
      - ./src/:/home/node/app/src/
networks:
  my-network:
    driver: bridge
    